@startuml
title UC0b - Accesso al Sistema
skinparam actorStyle awesome
actor "Cliente / Negoziante" as Utenti
participant "Interfaccia_Login" <<boundary>>
participant "Sistema di Accesso" as Sistema <<control>>
participant "UtenteRepository" as Repo <<repository>>
participant "Utente" <<entity>> 

Utenti -> Interfaccia_Login : Accede alla pagina di login
activate Interfaccia_Login
Interfaccia_Login -> Utenti : Richiede username/e-mail e password
deactivate Interfaccia_Login

Utenti -> Interfaccia_Login : Inserisce credenziali
activate Interfaccia_Login
Interfaccia_Login -> Sistema : Invia credenziali
activate Sistema
deactivate Interfaccia_Login


Sistema -> Repo : inviaCredenziali(username, password)
activate Repo
Repo --> Sistema : utilizzatore (Utenti o null)
deactivate Repo

alt Credenziali errate (utilizzatore== null)
    Sistema -> Interfaccia_Login : Messaggio "Username o password non validi"
    activate Interfaccia_Login
    Interfaccia_Login -> Utenti : Mostra errore
    deactivate Interfaccia_Login
else Credenziali corrette (utilizzatore != null)
    
    
    Sistema -> Utente : reindirizzaRuolo()
    activate Utente
    Utente --> Sistema : ruolo (Cliente/Negoziante)
    deactivate Utente

    alt ruolo == "Cliente"
        Sistema -> Sistema : impostaSessione("Cliente")
        Sistema -> Interfaccia_Login : Reindirizza a Dashboard Cliente
        activate Interfaccia_Login
        Interfaccia_Login -> Utenti : Mostra Dashboard Cliente
        deactivate Interfaccia_Login
    else ruolo == "Negoziante"
        Sistema -> Sistema : impostaSessione("Negoziante")
        Sistema -> Interfaccia_Login : Reindirizza a Dashboard Negoziante
        activate Interfaccia_Login
        Interfaccia_Login -> Utenti : Mostra Dashboard Negoziante
        deactivate Interfaccia_Login
    end
end

deactivate Sistema
@enduml

