@startuml
title UC12a - Aggiungere nuovo fornitore
skinparam actorStyle awesome

actor "Negoziante" as N
participant "InterfacciaNegoziante" as IN <<boundary>>
participant "GestoreFornitori" as G <<control>>
participant "CatalogoFornitori" as CF <<repository>>
participant "Fornitore" as F <<entity>>

N -> IN: Accede a "Gestione Fornitori"
activate IN
IN -> G: visualizzaListaFornitori()
activate G
G -> CF: cercaFornitori()
activate CF
CF -> F: findAll()
activate F
F --> CF: listaFornitori
deactivate F
CF --> G: elencoFornitori
deactivate CF
G --> IN: elencoFornitori
IN --> N: Mostra elenco fornitori
deactivate G
deactivate IN

N -> IN: Clicca "Aggiungi nuovo fornitore"
activate IN
IN -> IN: Mostra modulo inserimento
deactivate IN
N -> IN: Inserisce dati fornitore (nome, contatti, tipologiaMerce, servizioDomicilio)

break Annullamento
    N -> IN: Clicca "Annulla"
    activate IN
    IN -> IN: Chiudi modulo
    IN --> N: Mostra "Operazione annullata"
    deactivate IN
end

activate IN
IN -> G: aggiungiFornitore(datiFornitore)
activate G
G -> G: validaDatiFornitore(datiFornitore)

alt dati non validi (campi mancanti o formato errato)
    G --> IN: errore "Dati fornitori non validi"
    IN --> N: Mostra errore
    
else dati validi
    G -> CF: salvaFornitore(datiFornitore)
    activate CF
    CF -> F: <<create>> Fornitore
    activate F
    deactivate F
    CF --> G: NuovoFornitore
    deactivate CF
    G --> IN: messaggio "Fornitore aggiunto con successo"
    IN --> N: Mostra messaggio
end

IN -> G: aggiornaListaFornitori()
G -> CF: cercaFornitori()
activate CF
CF -> F: findAll()
activate F
F --> CF: listaFornitoriAggiornata
deactivate F
CF --> G: elencoAggiornato
deactivate CF
G --> IN: elencoAggiornato
IN --> N: Mostra elenco aggiornato

deactivate G
deactivate IN
@enduml