@startuml
title UC1a - Inviare richiesta preventivo/appuntamento
skinparam actorStyle awesome
actor Cliente
participant "Interfaccia Cliente" as UI <<boundary>>
participant "Sistema Richieste" as S <<control>>
participant "ArchivioRichieste" as Repo <<repository>>
participant "Richiesta" as R <<entity>>


Cliente -> UI : clicca "Richiedi appuntamento/preventivo"
UI -> S : richiediOpzioni()
activate S
S --> UI : listaOpzioni (Appuntamento, Preventivo)
deactivate S

Cliente -> UI : seleziona tipo richiesta

alt opzione = Appuntamento
    UI -> Cliente : mostra Campi1 (data, fascia oraria)
    Cliente -> UI : inserisce Campi1
else opzione = Preventivo
    UI -> Cliente : mostra Campi2 (contatti, descrizione evento)
    Cliente -> UI : inserisce Campi2
end

Cliente -> UI : clicca "Conferma"
UI -> S : inviaRichiesta(richiesta)
activate S

create R
S -> R : <<create>> Richiesta(richiesta)

S -> Repo : salvaRichiesta(Richiesta)
activate Repo
Repo --> S : conferma
deactivate Repo

S --> UI : messaggio:"In attesa di visualizzazione"
deactivate S

UI --> Cliente : mostraMessaggio("In attesa di visualizzazione")

@enduml
