@startuml
skinparam actorStyle awesome
title UC4 - Visualizzare orari di apertura e chiusura
skinparam actorStyle awesome
actor Cliente
participant "InterfacciaCliente" <<boundary>>
participant "SistemaInfoNegozio" <<control>>
participant "CatalogoOrari" as Repo <<repository>>
participant "Orario" as ORA <<entity>> 

Cliente -> InterfacciaCliente : Accede alla sezione "Orari del negozio"
activate InterfacciaCliente

InterfacciaCliente -> SistemaInfoNegozio : richiediOrari()
activate SistemaInfoNegozio

SistemaInfoNegozio -> Repo : getOrariSettimanali()
activate Repo
Repo --> SistemaInfoNegozio : listaOrari (ListaOrario)
deactivate Repo

loop per ogni giorno della settimana
    SistemaInfoNegozio -> "ORA" : getDettagliOrario()
    activate "ORA"
    "ORA" --> SistemaInfoNegozio : giorno, apertura, chiusura
    deactivate "ORA"
end

SistemaInfoNegozio --> InterfacciaCliente : mostraTabellaOrari(dati)
deactivate SistemaInfoNegozio

InterfacciaCliente -> Cliente : Visualizza tabella 
deactivate InterfacciaCliente


@enduml
