@startuml
skinparam actorStyle awesome
title UC5 - Visualizzare catalogo articoli

actor Cliente
participant "Interfaccia Catalogo" <<boundary>>
participant "Sistema Catalogo" <<control>>
participant "ArticoloRepository" <<repository>>
participant "Articolo" <<entity>>

Cliente -> "Interfaccia Catalogo" : accede alla sezione catalogo
"Interfaccia Catalogo" -> "Sistema Catalogo" : visualizzaCatalogo()

activate "Sistema Catalogo"


"Sistema Catalogo" -> "ArticoloRepository" : getArticoliDisponibili()
"ArticoloRepository" --> "Sistema Catalogo" : listaArticoli

alt listaArticoli vuota
    "Sistema Catalogo" --> "Interfaccia Catalogo" : esitoVuoto
    "Interfaccia Catalogo"--> Cliente : mostra("Nessun articolo disponibile")
else listaArticoli non vuota
    "Sistema Catalogo" --> "Interfaccia Catalogo" : listaArticoli
    
    
    Cliente -> "Interfaccia Catalogo" : selezionaArticolo(idArticolo)
    "Interfaccia Catalogo" -> "Sistema Catalogo" : richiediDettagli(idArticolo)
    
    "Sistema Catalogo" -> "ArticoloRepository" : trovaPerId(idArticolo)
    "ArticoloRepository" --> "Sistema Catalogo" : articolo
    
    "Sistema Catalogo" -> "Articolo" : getDettagli(Nome, Descrizione, Prezzo)
    "Articolo" --> "Sistema Catalogo" : dettagli
    
    "Sistema Catalogo" --> "Interfaccia Catalogo" : dettagli
end

deactivate "Sistema Catalogo"

"Interfaccia Catalogo" --> Cliente : mostraDettagli(dettagli)

@enduml