@startuml
skinparam actorStyle awesome
title UC5 - Visualizzare catalogo articoli

actor Cliente
participant "InterfacciaCliente" <<boundary>>
participant "SistemaCatalogo" <<control>>
participant "CatalogoArticoli" <<repository>>
participant "Articolo" <<entity>>

Cliente -> InterfacciaCliente : accede alla sezione catalogo
InterfacciaCliente -> SistemaCatalogo : visualizzaCatalogo()

activate SistemaCatalogo

SistemaCatalogo -> CatalogoArticoli : getArticoliDisponibili()
CatalogoArticoli --> SistemaCatalogo : listaArticoli

alt listaArticoli vuota
    SistemaCatalogo --> InterfacciaCliente : esitoVuoto
    InterfacciaCliente --> Cliente : mostra("Nessun articolo disponibile")
else listaArticoli non vuota
    SistemaCatalogo --> InterfacciaCliente : listaArticoli

    Cliente -> InterfacciaCliente : selezionaArticolo(idArticolo)
    InterfacciaCliente -> SistemaCatalogo : richiediDettagli(idArticolo)

    SistemaCatalogo -> CatalogoArticoli : trovaPerId(idArticolo)
    CatalogoArticoli --> SistemaCatalogo : articolo
    SistemaCatalogo -> CatalogoArticoli : verificaArticolo()
    activate CatalogoArticoli
    CatalogoArticoli --> SistemaCatalogo : articoloValido (Boolean)
    deactivate CatalogoArticoli
    SistemaCatalogo -> SistemaCatalogo : PrezzoF(idArticolo)

    SistemaCatalogo -> Articolo : getDettagli()
    Articolo --> SistemaCatalogo : dettagli

    SistemaCatalogo --> InterfacciaCliente : dettagli
end

deactivate SistemaCatalogo

InterfacciaCliente --> Cliente : mostraDettagli(dettagli)

@enduml