@startuml

skinparam actorStyle awesome
title UC6 - Visualizzare sconti, promozioni

actor Cliente
participant "InterfacciaCliente" as Boundary <<boundary>>
participant "SistemaOfferte" as Control <<control>>
participant "CatalogoOfferte" as Repo <<repository>>

Cliente -> Boundary : seleziona "Offerte e promozioni"
activate Boundary

Boundary -> Control : recuperaOfferteAttive()
activate Control

Control -> Repo : cercaOfferteValide()
activate Repo
Repo --> Control : elenco delle offerte valide
deactivate Repo

alt nessuna offerta attiva
    Control --> Boundary : lista offerte (null)
    Boundary --> Cliente : "Nessuna promozione attiva al momento"
else sono presenti offerte attive
    Control --> Boundary : elenco delle offerte valide
    Boundary --> Cliente : mostra elenco offerte disponibili
    
    Cliente -> Boundary : seleziona una specifica offerta(idOfferta)
    Boundary -> Control: visualizzaDettagliOfferta(idOfferta)
    
    Control -> Repo : trovaPerId(idOfferta)
    activate Repo
    Repo --> Control : offerta
    deactivate Repo
    
    Control --> Boundary : dettagli offerta
    Boundary --> Cliente : mostra dettagli dell'offerta
end

deactivate Control
deactivate Boundary

@endluml
