@startuml
title UC9a - Aggiungere articolo
skinparam actorStyle awesome

actor "Negoziante" as N
participant "InterfacciaNegoziante" as IN <<boundary>>
participant "GestoreCatalogo" as G <<control>>
participant "CatalogoArticolo" as CA <<repository>>
participant "Articolo" as Articolo <<entity>>

N -> IN: Accede a "Gestione Catalogo"
activate IN
IN -> G: visualizzaCatalogo()
activate G
G -> CA: mostraCatalogo()
activate CA
CA --> IN: Elenco articoli
deactivate G
deactivate CA
IN --> N: Mostra catalogo

deactivate IN

N -> IN: Clicca "Aggiungi nuovo articolo"
activate IN
IN -> IN: Mostra modulo inserimento


break annullamento
    N -> IN: Clicca "Annulla"
    
    IN -> G: annullaCreazione()
    activate G
    G --> IN: operazione annullata
    deactivate G
    IN --> N: Mostra "Operazione annullata"
    deactivate IN
end

N -> IN: Inserisce dati articolo e clicca "Conferma"
activate IN
IN -> G: aggiungiArticolo(dati)
activate G

G -> Articolo: <<create>> Articolo(dati)
activate Articolo
deactivate Articolo

alt dati non validi
    G --> IN: errore "Dati non validi"
    IN --> N: Mostra errore
    
else articolo duplicato
    G --> IN: errore "Articolo già esistente"
    IN --> N: Mostra errore
    
else dati validi
    G -> CA: aggiornaCatalogo()
    activate CA
    CA --> G: Articolo aggiunto
    deactivate CA
    G --> IN: conferma "Articolo aggiunto"
    IN --> N: Mostra conferma
end

deactivate G
deactivate IN

@enduml