@startuml
title UC9c - Rimozione di un articolo
skinparam actorStyle awesome
actor "Negoziante" as N
participant "InterfacciaNegoziante" as IN <<boundary>>
participant "GestoreCatalogo" as G <<control>>
participant "CatalogoArticolo" as CA <<repository>>
participant "Articolo" as Articolo <<entity>>

N -> IN: Accede a "Gestione Catalogo"
IN -> G: visualizzaCatalogo()
G -> CA: mostraCatalogo()
CA --> G: Mostra elenco articoli 
G --> IN: elenco articoli
IN --> N: Mostra catalogo

N -> IN: Seleziona articolo da rimuovere
N -> IN: Clicca "Rimuovi"

IN -> G: richiediConfermaRimozione()
G --> IN: dati articolo
IN --> N: "Sei sicuro? [Conferma/Annulla]"

break Annullamento
    N -> IN: Clicca "Annulla"
    IN --> N: Mostra "Operazione annullata"
end
alt Negoziante conferma
    IN -> G: rimuoviArticolo(id : Long)
    G -> CA: verificaArticolo()
    alt Articolo non esiste
        G --> IN: errore "Articolo non trovato"
        IN --> N: Mostra errore
        
    else Articolo esiste
    G -> CA: rimuoviArticolo()
    CA -> Articolo: <<destroy>> Rimuovi Articolo
    CA --> G: Articolo rimosso
    G --> IN: conferma rimozione
    IN --> N: Mostra "Articolo rimosso"
            IN -> G: aggiornaCatalogo()
        G -> CA: mostraCatalogo()
        CA --> G: elenco articoli aggiornato 
        G --> IN: elenco aggiornato
        IN --> N: Mostra catalogo aggiornato

    end
end
