@startuml
title UC9c - Rimuovere articolo
skinparam actorStyle awesome

actor "Negoziante" as N
participant "InterfacciaNegoziante" as IN <<boundary>>
participant "GestoreCatalogo" as GC <<control>>
participant "CatalogoArticoli" as CA <<repository>>
participant "Articolo" as A <<entity>>

N -> IN: Accede a "Gestione Catalogo"
activate IN
IN -> GC: visualizzaCatalogo()
activate G
GC -> CA: mostraCatalogo()
activate CA
CA --> GC: Mostra elenco articoli 
deactivate CA
GC --> IN: elenco articoli
IN --> N: Mostra catalogo
deactivate GC
deactivate IN
N -> IN: Seleziona articolo da rimuovere
activate IN
IN -> GC: getArticolo(id)
activate GC
GC -> CA: trovaPerId(id)
activate CA
CA --> GC: articolo
deactivate CA
GC --> IN: dettagli articolo
deactivate GC
IN --> N: mostra dettagli e chiede conferma

N -> IN: Conferma rimozione
IN -> GC: rimuoviArticolo(id)
activate GC

GC -> CA: trovaperId
activate CA
CA --> GC: articolo (o None)
deactivate CA

alt articolo non trovato
    GC --> IN: ValueError "Articolo con id={id} non trovato."
    IN --> N: mostraErrore()
else articolo trovato
    GC -> A: rimuoviOfferta()
    GC -> CA: rimuoviArticolo()
    activate CA
    CA --> GC: conferma
    deactivate CA

    GC --> IN: esito positivo
    deactivate GC
    IN --> N: mostra "Articolo rimosso con successo"
end

deactivate IN
@enduml