@startuml

title Caso d'uso: Registrazione cliente (UC0a)

start

:Richiedi username, e-mail e password;

repeat
  :Inserisci username, e-mail e password;
  :Conferma password;
  
  if (Username univoco?) then (no [Username già in uso])
    :Mostra errore "Username già in uso";
    label lab1
  elseif (E-mail valida?) then (no [Formato non valido])
    :Mostra errore "Inserire email valida";
    label lab2
  elseif (Password rispetta criteri?) then (no [Criteri non rispettati])
    :Mostra criteri di complessità;
    label lab3
  elseif (Password coincidono?) then (no [Le password non corrispondono])
    :Mostra errore "Le password non corrispondono";
    label lab4
  else (sì [Tutti i dati validi])
    label dati_validi
  end if

backward:Dati non validi;
repeat while (Dati validi?) is (no) not (sì)

:Salva account Cliente nel database;
:Mostra "Account Cliente creato con successo";
:Reindirizza alla pagina di login;

stop
@enduml
