@startuml
title UC11 - Aggiornare Orari Apertira Chiusura
start
:Il Negoziante accede a "Gestione orari";
:Il sistema mostra la tabella orari;
repeat
:Il Negoziante seleziona un giorno/data;

if (Giorno della settimana?)
  :Modifica apertura/chiusura;
  :Conferma modifiche;
  :Sistema valida modifiche;
elseif (Giorno festivo)
  :Seleziona "Chiuso";
  :Conferma;
elseif (Orario straordinario)
  :Imposta apertura/chiusura speciale;
  :Sistema valida modifiche;
endif

if (Dati validi?) then (no)
  :Mostra errore;
else (si)
  :Salva modifiche;
  :Messaggio "Orario aggiornato con successo";
  stop
endif
@enduml