@startuml

title UC4 - Visualizzare orari
start

:Accesso alla sezione "Orari del negozio";

:Accesso alla lista orari settimanali all'archivio;
:Il sistema recupera l'elenco completo dei giorni;

:Elaborazione dei dettagli per ogni giorno della settimana;
:Recupero dati specifici dall'oggetto Orario (giorno, apertura, chiusura);

:Generazione della tabella orari riepilogativa;
:Visualizzazione della tabella orari al cliente;

stop
@enduml
