@startuml

title UC5 - Visualizzare catalogo articoli 

start

:Selezione sezione "Catalogo" (Interfaccia);

:Il sistema interroga l'archivio articoli;

if (Articoli presenti nell'archivio?) then (no)
  
  :Messaggio "Nessun articolo disponibile al momento";
  
else (si)
  :Visualizzazione elenco sintetico articoli;
  :Selezione di un articolo specifico dal catalogo;
  
  :Recupero dati oggetto (Nome, Descrizione, Prezzo, Disponibilità);
  :Visualizzazione scheda dettaglio articolo;
  
endif
stop
@enduml
