@startuml
title UC9c: Rimuovere articolo
start
:Il negoziante accede alla sezione "Gestione Catalogo";
:Il sistema visualizza l'elenco degli articoli presenti;
:Il negoziante seleziona l'articolo da rimuovere;
:Il negoziante clicca su "Rimuovi";
:Il sistema richiede conferma:
"Sei sicuro di voler rimuovere l'articolo selezionato?";

if (Conferma?) then (Sì)
  :Il sistema rimuove l'articolo dal catalogo attivo;
  :L'articolo non è più visualizzabile dai clienti ;
  :Messaggio di conferma operazione;
  
else (No - Annulla)
  :Il sistema chiude la finestra di conferma;
  :Messaggio "Operazione annullata";
  :L'articolo rimane nel catalogo;
  
endif
stop 
@enduml