@startuml
skinparam linethipe ortho

title Caso d'uso: Registrazione cliente (UC0a)

start

:Richiedi username, e-mail e password;

repeat
    :Inserisci username, e-mail e password;
    :Conferma password;

    
    if (Username univoco?) then (no [Username già in uso])
        :Mostra errore "Username già in uso";
    elseif (E-mail valida?) then (no [Formato non valido])
        :Mostra errore "Inserire email valida";
    elseif (Password rispetta criteri?) then (no [Criteri non rispettati])
        :Mostra criteri di complessità;
    elseif (Password coincidono?) then (no [Le password non corrispondono])
        :Mostra errore "Le password non corrispondono";
    else (sì [Tutti i dati validi])
        
        
        break
        
    endif
    
repeat while (Dati non validi)


:Salva account Cliente nel database;
:Mostra "Account Cliente creato con successo";
:Reindirizza alla pagina di login;

stop
@endum

