@startuml
left to right direction
skinparam actorStyle awesome


package "Gestione Negozio" {
  Negoziante -- (UC7: Gestione Notifiche Richieste)
  
  (UC8: Aggiornare Stato Consegna) ..> (UC7) : <<extend>>
  Negoziante -- (UC8: Aggiornare Stato Consegna)
  Negoziante -- (UC9a: Aggiungere Articolo)
  Negoziante -- (UC9b: Modificare Articolo)
  Negoziante -- (UC9c: Rimuovere Articolo)
  
  Negoziante -- (UC10a: Creare Sconto)
  Negoziante -- (UC10b: Creazione Promozione)
  Negoziante -- (UC10c: Eliminare Sconto o Promozione)
  
  Negoziante -- (UC11: Aggiornare Orari)
  Negoziante -- (UC12: Gestione Fornitori)
}
@enduml