@startuml
left to right direction
skinparam actorStyle awesome
title Package: Servizi Cliente

actor Cliente

package "Servizi Cliente" {  
  Cliente -- (UC1a: Inviare Richiesta Preventivo/Appunt.)
  (UC1a: Inviare Richiesta Preventivo/Appunt.) ..> (UC3) : <<include>>
  Cliente -- (UC1b: Ricevere Conferma Richiesta)
  Cliente -- (UC1c: Annullare Richiesta)
  Cliente -- (UC2a: Inviare Richiesta Consegna)
  (UC2a: Inviare Richiesta Consegna) ..> (UC3) : <<include>>
  Cliente -- (UC2b: Ricevere Stato Consegna)
  Cliente -- (UC3: Scegliere Data e Fascia Oraria)
  Cliente -- (UC4: Visualizzare Orari)
  Cliente -- (UC5: Visualizzare Catalogo Articoli)
  Cliente -- (UC6: Visualizzare Sconti e Promozioni)

}
@enduml
