@startuml
left to right direction
skinparam actorStyle awesome

actor Cliente
actor Negoziante

package "Locale" {

  Cliente -- (UC4: Visualizzare orari)
  Cliente -- (UC5: Visualizzare catalogo articoli)
  Cliente -- (UC6: Visualizzare sconti e promozioni)

  Negoziante -- (UC9a: Aggiungere articolo)
  Negoziante -- (UC9b: Modificare articolo)
  Negoziante -- (UC9c: Rimuovere articolo)
  Negoziante -- (UC10a: Creare sconto)
  Negoziante -- (UC10b: Creare promozione)
  Negoziante -- (UC10c: Eliminare sconto o promozione)
  Negoziante -- (UC11: Aggiornare orari)
}
@enduml