@startuml
left to right direction
skinparam actorStyle awesome

actor Utente
actor Cliente
actor Negoziante
actor Amministratore

Utente <|-- Cliente
Utente <|-- Negoziante

package "Autenticazione" {
  Cliente -- (UC0a: Registrazione Cliente)
  (UC0b: Accesso Utente) -- Utente
  (UC0b: Accesso Utente) -- Amministratore
  Amministratore -- (Creazione Account Negoziante)
}
@enduml
