@startuml
left to right direction
skinparam actorStyle awesome

actor Utente
actor Cliente
actor Negoziante
actor Amministratore

Utente <|-- Cliente
Utente <|-- Negoziante

package "Autenticazione" {
  Cliente -- (UC0a: Registrazione Cliente)
  (UC0b: Accesso Utente) -- Utente
}

Amministratore -- (Creazione Account Negoziante)
(Creazione Account Negoziante) ..> Negoziante : <<creates>>
@enduml