@startuml
left to right direction
skinparam actorStyle awesome

actor Negoziante

package "Fornitori" {
  Negoziante -- (UC12a: Aggiungere fornitore)
  Negoziante -- (UC12b: Aggiornare elenco fornitori)
  Negoziante -- (UC12c: Eliminare fornitore)
  Negoziante -- (UC13: Visualizzazione lista fornitori)
}
@enduml
